// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/djx30103/vpsub/internal/config"
	"github.com/djx30103/vpsub/internal/handler"
	"github.com/djx30103/vpsub/internal/server"
	"github.com/djx30103/vpsub/internal/server/router"
	"github.com/djx30103/vpsub/pkg/app"
	"github.com/djx30103/vpsub/pkg/log"
	"github.com/google/wire"
)

// Injectors from wire.go:

func NewApp(appConfig *config.AppConfig, logger *log.Logger) (*app.App, func(), error) {
	handlerHandler := handler.NewHandler(logger, appConfig)
	subscribeHandler := handler.NewSubscribeHandler(handlerHandler, appConfig)
	routerRouter := router.NewRouter(logger, subscribeHandler, appConfig)
	httpServer := server.NewHTTPServer(logger, appConfig, routerRouter)
	appApp := newApp(httpServer)
	return appApp, func() {
	}, nil
}

// wire.go:

var DataSet = wire.NewSet()

var ServerSet = wire.NewSet(server.NewHTTPServer)

var RouterSet = wire.NewSet(router.NewRouter)

var UserHandlerSet = wire.NewSet(handler.NewHandler, handler.NewSubscribeHandler)
